### ISSUE TITLE
See if it's possible to reduce diff noise in Terraform plans

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/cli#434]
In this plan: https://github.com/overmindtech/terraform-example/actions/runs/9342404304/job/25710470861#step:5:131 we see that we are going to replace an EC2 instance and as a result there are a lot of fields that are `(known after apply)`. We need to see if it's possible to work out which these are and treat them differently when calculating an `ItemDiff`. I think probably the best thing to do here is simply remove them

**Comment by dylanratcliffe** [comment]
For my initial investigation I'm using a plan that replaces EC2 instances, you can see in there plan there are a number of `(known after apply)` changes:

```
 # module.scenarios[0].aws_instance.example_2 must be replaced
-/+ resource "aws_instance" "example_2" {
      ~ ami                                  = "ami-0552499a7e7b17069" -> "ami-07c8095f365849684" # forces replacement
      ~ arn                                  = "arn:aws:ec2:eu-west-2:540044833068:instance/i-00675698f414b3dfd" -> (known after apply)
      ~ associate_public_ip_address          = true -> (known after apply)
      ~ availability_zone                    = "eu-west-2a" -> (known after apply)
      ~ cpu_core_count                       = 1 -> (known after apply)
      ~ cpu_threads_per_core                 = 2 -> (known after apply)
      ~ disable_api_stop                     = false -> (known after apply)
      ~ disable_api_termination              = false -> (known after apply)
      ~ ebs_optimized                        = false -> (known after apply)
      - hibernation                          = false -> null
      + host_id                              = (known after apply)
      + host_resource_group_arn              = (known after apply)
      + iam_instance_profile                 = (known after apply)
      ~ id                                   = "i-00675698f414b3dfd" -> (known after apply)
      ~ instance_initiated_shutdown_behavior = "stop" -> (known after apply)
      + instance_lifecycle                   = (known after apply)
```

Interestingly these have a number of different states:

* Changed (`~`)
* Added (`-`)

There are also a few things like `hibernation` and `credit_specification.cpu_credits` which are being changed to `null`. I'm not sure why this might be, potentially these are read-only attributes or something?

## Tasks

* [ ] Investigate what is different in the JSON plan about (known after apply) resources
* [ ] Investigate what is common about `hibernation` and `credit_specification.cpu_credits` such that they are shown as being removed rather than known after apply
* [ ] Double check the behaviour for nested groups. It's very common for something like `ebs_block_device` to be considered "modified" (known after apply) with all of the attributes underneath being "added" (known after apply). We just need to make sure that we are handling this well

**Comment by dylanratcliffe** [comment]
Seems the best way to deal with this is to look at the `resource_changes` section, we have the `before`, `after` and `after_unknown`. So presumably if we delete the `after_unknown` from both sides, then diff, we should get the diff we actually want. After doing this we get the following:

Before

```json
{
    "ami": "ami-0552499a7e7b17069",
    "get_password_data": false,
    "hibernation": false,
    "instance_type": "t3.micro",
    "source_dest_check": true,
    "timeouts": null,
    "user_data_replace_on_change": false,
    "volume_tags": null
}
```

After

```json
{
    "ami": "ami-07c8095f365849684",
    "get_password_data": false,
    "hibernation": null,
    "instance_type": "t3.micro",
    "source_dest_check": true,
    "timeouts": null,
    "user_data_replace_on_change": false,
    "volume_tags": null
}
```

Meaning that the diff is as expected, the AMI changes, and `hibernation` changes from `false` to `null`

**Comment by dylanratcliffe** [comment]
Regarding arrays and maps in the `after_unknown` section: Maps seem to be just a nested version of the way the top level works i.e. *"unknown leaf values replaced with true, and all known leaf values omitted"*, however the meaning of an empty array here isn't clear to me. If the entire value of an array is unknown, it'll be replaced with true, but if it's an empty array I'm assuming that means it's possible that some of the array values are known after apply and some aren't? I think for now the best course of action is to just ignore this and assume that an empty array means that the values aren't "known after apply"

**Comment by dylanratcliffe** [comment]
# Plan of Action

* [ ] Edit the test plans so that there is a test that includes this, and write a failing test
* [ ] Refactor `itemDiffFromResourceChange` to knock out these unknown changes first
* [ ] Create a ticket to do a POC to see if it's possible to differentiate code changes vs drift vs data changes
