### ISSUE TITLE
Create milestones to better track errors

### ISSUE THREAD

**Issue by dylanratcliffe** [overmindtech/cli#470]
## Overmind Terraform Plan

We're seeing a number of users hit issues, but it's hard to track what caused them. To this end we should add some additional milestones to the root span as events so that we can logically see how far the process got before it failed. These could be:

* [x] Authenticated
* [x] Configured AWS
* [x] Finished `terraform plan`
  * [x] Also if this fails, capture the error
* [x] Finished cache warmup
* [x] Finished blast radius
* [x] Got risks

At each step we should include as much information as possible so that it's clear to imagine what the issue would have looked like for the user and where we need to be looking to fix it
